
    create table cidade (
       id int8 generated by default as identity,
        nome varchar(80) not null,
        estado_id int8 not null,
        primary key (id)
    );

    create table cozinha (
       id int8 generated by default as identity,
        nome varchar(80),
        primary key (id)
    );

    create table estado (
       id int8 generated by default as identity,
        nome varchar(255) not null,
        primary key (id)
    );

    create table forma_pagamento (
       id int8 generated by default as identity,
        descricao varchar(60) not null,
        primary key (id)
    );

    create table grupo (
       id int8 generated by default as identity,
       nome varchar(60) not null,
        primary key (id)
    );

    create table grupo_permissao (
       grupo_id int8 not null,
        permissao_id int8 not null
    );

    create table item_pedido (
       id int8 generated by default as identity,
        observacao varchar(255),
        preco_total numeric(19, 2),
        preco_unitario numeric(19, 2),
        quantidade int4,
        pedido_id int8 not null,
        produto_id int8 not null,
        primary key (id)
    );

    create table pedido (
       id int8 generated by default as identity,
        data_cancelamento timestamp,
        data_confirmacao timestamp,
        data_criacao timestamp,
        data_entrega timestamp,
        endereco_bairro varchar(60),
        endereco_cep varchar(9),
        endereco_complemento varchar(60),
        endereco_logradouro varchar(100),
        endereco_numero varchar(20),
        status int4,
        subtotal numeric(19, 2),
        taxa_frete numeric(19, 2),
        valor_total numeric(19, 2),
        usuario_cliente_id int8 not null,
        endereco_cidade_id int8,
        forma_pagamento_id int8 not null,
        restaurante_id int8 not null,
        primary key (id)
    );

    create table permissao (
       id int8 generated by default as identity,
        descricao varchar(60) not null,
        nome varchar(100) not null,
        primary key (id)
    );

    create table produto (
       id int8 generated by default as identity,
        ativo boolean not null,
        descricao varchar(255) not null,
        nome varchar(80) not null,
        preco numeric(19, 2) not null,
        restaurante_id int8 not null,
        primary key (id)
    );

    create table restaurante (
       id int8 generated by default as identity,
        data_atualizacao timestamp not null,
        data_criacao timestamp not null,
        endereco_bairro varchar(60),
        endereco_cep varchar(9),
        endereco_complemento varchar(60),
        endereco_logradouro varchar(100),
        endereco_numero varchar(20),
        nome varchar(80) not null,
        taxa_frete numeric(19, 2),
        cozinha_id int8 not null,
        endereco_cidade_id int8,
        primary key (id)
    );

    create table restaurante_forma_pagamento (
       restaurante_id int8 not null,
        forma_pagamento_id int8 not null
    );

    create table usuario (
       id int8 generated by default as identity,
        data_cadastro timestamp not null,
        email varchar(255) not null,
        nome varchar(80) not null,
        senha varchar(255) not null,
        primary key (id)
    );

    create table usuario_grupo (
       usuario_id int8 not null,
        grupo_id int8 not null
    );

    alter table if exists cidade 
       add constraint fk_cidade_estado 
       foreign key (estado_id) 
       references estado;

    alter table if exists grupo_permissao 
       add constraint fk_grupo_permissao_permissao 
       foreign key (permissao_id) 
       references permissao;

    alter table if exists grupo_permissao 
       add constraint fk_grupo_permissao_grupo
       foreign key (grupo_id) 
       references grupo;

    alter table if exists item_pedido 
       add constraint fk_item_pedido_pedido
       foreign key (pedido_id) 
       references pedido;

    alter table if exists item_pedido 
       add constraint fk_item_pedido_produto
       foreign key (produto_id) 
       references produto;

    alter table if exists pedido 
       add constraint fk_pedido_usuario 
       foreign key (usuario_cliente_id) 
       references usuario;

    alter table if exists pedido 
       add constraint fk_pedido_cidade
       foreign key (endereco_cidade_id) 
       references cidade;

    alter table if exists pedido 
       add constraint fk_pedido_forma_pagamento 
       foreign key (forma_pagamento_id) 
       references forma_pagamento;

    alter table if exists pedido 
       add constraint fk_pedido_restaurante
       foreign key (restaurante_id) 
       references restaurante;

    alter table if exists produto 
       add constraint fk_produto_restaurante 
       foreign key (restaurante_id) 
       references restaurante;

    alter table if exists restaurante 
       add constraint fk_restaurante_cozinha 
       foreign key (cozinha_id) 
       references cozinha;

    alter table if exists restaurante 
       add constraint fk_restaurante_cidade
       foreign key (endereco_cidade_id) 
       references cidade;

    alter table if exists restaurante_forma_pagamento 
       add constraint fk_restaurante_forma_pagamento_forma_pagamento 
       foreign key (forma_pagamento_id) 
       references forma_pagamento;

    alter table if exists restaurante_forma_pagamento 
       add constraint fk_restaurante_forma_pagamento_restaurante 
       foreign key (restaurante_id) 
       references restaurante;

    alter table if exists usuario_grupo 
       add constraint fk_usuario_grupo_grupo 
       foreign key (grupo_id) 
       references grupo;

    alter table if exists usuario_grupo 
       add constraint usuario_grupo_usuario 
       foreign key (usuario_id) 
       references usuario;